### ISSUE TITLE
How will we implement type checking for match expressions?

### ISSUE THREAD

**Issue by SebastianMestre** [SebastianMestre/Jasper#129]
I don't know of a better place to put this, so it's going in github issue.

This space is just meant to discuss the implementation of typechecking for match expressions. I came up with a cool idea, and I think it's a possible solution. Furthermore, I believe the same idea applies to implementing record types as well.

There are two important parts related to typechecking a match expression: checking the matched-on value's type, and checking the type of the match expression itself.

It seems sensible to only do the first part only once the type of the matched-on
value is known. But, since the second part may depend on the result of the first
one, we end up with a whole bunch of order-dependance in the typechecker, which I
would rather not deal with...

I have thought about this a good deal, and I think I found a solution. Essentially, the idea is to extend the capabilities of the TCCore a bit more.

Here it goes:

### What is the problem we are trying to solve?

When we typecheck a match expression, we learn some things about the type of
the thing we are matching on. We may not learn its type, but we do learn some
facts that can be helpful in further type checking/deduction

Example:
```rust
x := fn (y) {
  return match (y) {
    a => 5;
    b => b;
  };
};
```

The match expression has fields "a" and "b", thus, we know that y must be of
union type with fields "a" and "b", but we do not know its actual type.

Also, we know that (since all branches of a match must have the same type),
the field `b` is of type `int`.

### What tools will we use?

First, I introduce the idea of a dummy-union. This is a form of typefunc whose
only purpose is to help in unification.

A dummy-union has a list of all the identifiers that are known to be in a union
typefunc, along with their deduced monotype. It esentially represents a typefunc
which is known to be a union with (at least) certain fields, but whose identity
is not yet known.

When we unify two dummy-unions, we merge their information.

example:
```c++
unify_typefunc(
  DummyUnion{ {{ "a", mono_int() },
               { "b", mono_string() },
               { "c", new_var() }} },
  DummyUnion{ {{ "c", mono_int() }} });
```

gives as a result:

```c++
DummyUnion{ {{ "a", mono_int() },
             { "b", mono_string() },
             { "c", mono_int() }} };
```

When we unify a dummy-union with an union, we check that the dummy-union is
compatible with the union (i.e. that it doesn't have any extra fields, and that
the types of the fields can be unified)

example:

```c++
unify_typefunc(
  DummyUnion{ {{ "a", mono_int() },
               { "b", mono_string() }} },
  Union{ {{ "a", mono_int() },
          { "b", mono_string() },
          { "c", mono_int() }} });
```

gives as a result the original union:

```c++
Union{ {{ "a", mono_int() },
        { "b", mono_string() },
        { "c", mono_int() }} };
```
### can this be used to typecheck `match(){}`?

When we typecheck a match expression, we create a new dummy-union typefunc with
all the fields that were matched on.
We then unify this with the typefunc of the value we are matching on.

Going back to the example from before

```rust
x := fn (y) {
  return match (y) {
    a => 5;
    b => b;
  };
};
```
we can do a step by step of this program being typechecked:
```
typecheck x:
| typecheck fn (y) { ... }:
| | y : new_var()
| | return_type : new_var()
| |
| | typecheck return:
| | | typecheck match(y) { a; b; }:
| | | |   let du = new_dummy_union { {{ "a", new_var() },
| | | |                               { "b", new_var() }} }
| | | |   unify(typeof y, new_term(du, {}))
| | | |
| | | |   let x = newvar
| | | |   unify(x, typeof 5)   // we get int
| | | |   unify(x, typeof b)   // we learn that the field "b" of du has type int
| | | |   match(y) { ... } : x // the match returns an int
| | |
| | | unify(current_function().return_type, typeof match (y) { ... }) // we get int
|
| x : generalize(typeof fn (y) { ... }) // we get x : ( du(<>) ) -> int
```

At the end of typechecking, we can go over all the ast, and check whether anything
still has a dummy typefunc in its type. In which case, we can tell that we were
not able to do complete deduction, and we can emit an error.

**Comment by SebastianMestre** [comment]
any thoughts?

**Comment by lushoBarlett** [comment]
So, I understand, the dummy is just a holder of type information but it does not 'exist'. It's just the type deduction's best guess.

I don't think that's cool to just emit an error unless you searched all the defined type functions and no one matches that dummy, **then** you can say "this is an impossibility".

What I mean is, if this exists somewhere in the codebase
```rust
tf := union { a : int; b: int; };
```
then you should definitely not emit an error, because the dummy matches an existent type function. Not always you will find the actual type function lying around somewhere, sometimes the programmer will assume you know which one it is.

**Comment by lushoBarlett** [comment]
Quick question: once a name has been assigned a name, can it be changed further down the line? In Haskell, the name is a part of the type function if I'm not mistaken.

**Comment by SebastianMestre** [comment]
In my mental model, typefuncs are identity-based, and monotypes are value-based. that is:

```c++
// these are different types
t1 := union { a : int; b : int };
u1 := union { a : int; b : int };

// these are the same type
t2 := union { a : int; b : int };
u2 := t2;

// these are the same type
m1 := array(<int>);
m2 := array(<int>);
```
I think this is the sweet spot for type safety and convenience. Going too far the structural route sounds too unsafe, and going too far the nominal route sounds too restrictive (if you have nominal monotypes, things break down because you can't really do unification).

**Comment by SebastianMestre** [comment]
> So, I understand, the dummy is just a holder of type information but it does not 'exist'. It's just the type deduction's best guess.
> 
> I don't think that's cool to just emit an error unless you searched all the defined type functions and no one matches that dummy, **then** you can say "this is an impossibility".
> 
> What I mean is, if this exists somewhere in the codebase
> 
> ```rust
> tf := union { a : int; b: int; };
> ```
> 
> then you should definitely not emit an error, because the dummy matches an existent type function. Not always you will find the actual type function lying around somewhere, sometimes the programmer will assume you know which one it is.

Yeah, but what if there are two (or more) of them?  What if you add a new type, and suddenly a bunch of code becomes ambiguous because it relied on there being a single type that matched it?

Since it has to be a post-process pass anyways, and most of the infrastructure required for either option is pretty much the same, we can delay this choice for later. I think we should keep discussing tradeoffs

**Comment by SebastianMestre** [comment]
> Quick question: once a name has been assigned a name, can it be changed further down the line? In Haskell, the name is a part of the type function if I'm not mistaken.
> 
> E: what I mean is, does `union { name : type }` even mean anything on its own? Like an anonymous type function? Because then the type checking becomes structural.

You have that right. In my mind, that's an anonymous type function, which is useless. I guess the point where we disagree is that anonymous type funcs mean there must be structural typing.

Although it might be cool to have structural typing in some form, this is not it.

**Comment by SebastianMestre** [comment]
We got this pretty much figured out
