### ISSUE TITLE
Noisy warnings

### ISSUE THREAD

**Issue by SebastianMestre** [SebastianMestre/Jasper#134]
Currently, we use the same `ASTTag` to list out all the possible variants in both AST and TypedAST. This is starting to be a bit troublesome because the two are diverging, meaning that whenever we `switch` over a TypedAST's `type()`, we get a bunch of noisy warnings.

Of course, one could add a default case, but that is just treating the symptom. Furthermore, it silences the warning, opening up a way for bugs.

an example:

We don't need `TypeTerm`, `UnionExpression`, `StructExpression`, etc. `TypedAST` nodes. Instead, we need a node that holds a type function value, and a node that holds a mono type value (i.e. an int that is an index into one of the type system core arrays). This hypothetical node is definitely not needed in `AST`, further widening the gap.

E:

There is also the obvious example that we don't have `TypedAST::BinaryExpression`

**Comment by lushoBarlett** [comment]
The most obvious fix for this is creating a different tag system for typed ast
