### ISSUE TITLE
The architecture of the type checker is all wrong

### ISSUE THREAD

**Issue by SebastianMestre** [SebastianMestre/Jasper#145]
As it stands, the tc is not nice to work with. This is because it was built with a mental model that is completely backwards!

Now that we have a better idea of what things need it needs to do, we have a good opportunity to re-architect it.

### The problems

The biggest mistake is that the type checker is a member of the environment, and not the other way around. This is clear from how often we say `env.m_typechecker` in `typecheck`.

Another mistake is how the `TypeSystemCore` has too many responsibilities. For instance, `generalize` should be in the `TypeChecker`, instead (It takes the environment as an argument! wtf?!) . The core should only be responsible for unification.

Another thing is how the scope hierarchy is not stored explicitly. I feel like if we actually stored the scope tree, and a pointer to its surrounding scope on every `TypedAST` node, a bunch of things would be simplified.

### The proposal

Here goes a general mock-up of how things would look.

Another thing that needs addressing is how type functions can reference other type functions that come *after* them in the source code. I don't have a definitive solution to this yet, but I think the new architecture will make this easier to do.

```c++
struct TypedAST {
  TypedASTTag m_tag;
  MonoId m_value_type;
  Scope* m_surrounding_scope;
};

struct TypeChecker {
  TypeSystemCore m_core;
  CompileTimeEnvironment m_env;

  PolyId generalize(MonoId);
};

struct CompileTimeEnvironment {
  bucket_array<Scope> m_scopes;
  Scope m_global_scope;
  Scope* m_current_scope;
};

struct Scope {
  std::set<MonoId> m_mono_vars;
  std::map<std::string, Declaration> m_bindings;
};

struct TypeSystemCore {
  std::vector<MonoHeader> mono_header;
  // etc ...

  MonoId find(MonoId);
  void unify(MonoId, MonoId);

  TypeFuncId find_func(TypeFuncId);
  void unify_func(TypeFuncId, TypeFuncId);
};
```

There's probably more things that I haven't thought about. Thoughts?

**Comment by lushoBarlett** [comment]
I follow on the fact that TSC is big and that it would be better if it only stores and unifies data, because this is a very specific but "independent" thing to do. TC should be able to take care of the rest.

Flipping CTE and TC around, I can't really state my opinion on that, I should take a good look at the code first. But if you say that it should be done then it probably should be done, I trust your judgement for cleanness. I guess if the CTE is just a manager then it would make sense.

I would like to hear your reasoning as to why storing a scope pointer in each TypedAST node is good.

**Comment by SebastianMestre** [comment]
> I would like to hear your reasoning as to why storing a scope pointer in each TypedAST node is good.

If we stored the scope tree that `match_identifiers` implicitly builds, `typecheck` wouldn't have to do it again from scratch. (note how, currently, `typecheck` does a lot of the same scope management stuff that `match_identifiers` does)

**Comment by SebastianMestre** [comment]
I just remembered another important thing:

The whole `Frontend::Binding` idea is pretty bad. I did it like that because it seemed like the cleanest solution at the time, but, actually, differentiating between polymorphic and non-polymorphic declarations with a flag is a lot simpler and cleaner.

Not to mention that we need the flag to implement the hindley-milner [rec] rule anyways.
