### ISSUE TITLE
TypeFunctionData is ugly

### ISSUE THREAD

**Issue by lushoBarlett** [SebastianMestre/Jasper#156]
The TypeFunctionData struct holds every possible data that a type function could have. This is not ideal.

Something Seba showed once in a gist was to make it polymorphic and I liked it. Can this be done?

**Comment by SebastianMestre** [comment]
idk, go try it out

**Comment by SebastianMestre** [comment]
I would say to hold off on it for now. We don't know what the interface should be yet, so abstracting it away now will probably come back to bite us later.
