### ISSUE TITLE
Running the interpreter with no "source.jp" gives unclear error

### ISSUE THREAD

**Issue by EmmanuelMess** [SebastianMestre/Jasper#183]
This error: 

```
jasperi: src/interpreter/eval.cpp:176: void Interpreter::eval(TypedAST::CallExpression*, Interpreter::Environment&): Assertion `callee' failed.
Abortado (`core' generado)
```

Should probably be "No input file provided, please create 'source.jp'" instead, or an explanation on how to use the command.

**Comment by SebastianMestre** [comment]
We are not concerned with UX right now. This will be addressed in the future, though.

**Comment by SebastianMestre** [comment]
linking #208 here :)
