### ISSUE TITLE
Nested seq expressions are broken

### ISSUE THREAD

**Issue by lushoBarlett** [SebastianMestre/Jasper#240]
Exhibit 1:
```rust
a := seq {
    b := seq { return 0; };
    return b;
};
```
This will tell me `Assertion 'e.m_return_value' failed`. I don't know which one fails.

Exhibit 2:
```rust
a := seq {
    var := 0;
    b := seq {
        var = 1;
        return 0;
    };
    return b;
};
```
This fails while casting in `as<T>`. It tells me that `Assertion 'x' failed.`, meaning the pointer itself is `nullptr`. I have tried other kinds of sequence expression capture tests, more normal ones, and they work fine.

Further problems have not yet been found, I suppose that's it.

**Comment by SebastianMestre** [comment]
Yeah. I had run into this myself, and even figured out what was wrong, but now can't remember what the problem was anymore.

I'll re-debug it later today.

**Comment by SebastianMestre** [comment]
Here is part of the problem: For the purposes of `compute_offsets` we consider every identifier that isn't declared inside a function as a global variable. This is not true for seq expressions, as they can have their own local variables, while not being inside any functions.
